matrix:
  include:
    - language: node_js
      node_js:
        - '10'
      cache: yarn
      script:
        - yarn run build
        - yarn run type-check
        - yarn run test
        - yarn run lint
    - osx_image: xcode10.3
      language: objective-c
      before_install:
        - gem update --system
        - gem install bundler
        - brew install librsvg yarn java
      install: >-
        yarn install &&
        cd packages-ruby/polaris_icons &&
        bundle install &&
        bundle check
      script:
        - bundle exec rake convert_and_copy_gem_icons
        - bundle exec rake build
